// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlrkWMjIbTuVf4F7n-tt4YWdi_5z-tRX8',
    appId: '1:648016088742:web:812031f6843185f55b6e67',
    messagingSenderId: '648016088742',
    projectId: 'storyclub-4b1ad',
    authDomain: 'storyclub-4b1ad.firebaseapp.com',
    storageBucket: 'storyclub-4b1ad.firebasestorage.app',
    measurementId: 'G-0NSYPLDWCL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMApwhs4R1V5pFudF7JNY_iuZiWtLDrMU',
    appId: '1:648016088742:android:21509f717160a49e5b6e67',
    messagingSenderId: '648016088742',
    projectId: 'storyclub-4b1ad',
    storageBucket: 'storyclub-4b1ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8pFECr0LB5bUujeEace-xErxA9Q5BTN0',
    appId: '1:648016088742:ios:5ed86a0a1d9791c35b6e67',
    messagingSenderId: '648016088742',
    projectId: 'storyclub-4b1ad',
    storageBucket: 'storyclub-4b1ad.firebasestorage.app',
    iosBundleId: 'com.example.storyClub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8pFECr0LB5bUujeEace-xErxA9Q5BTN0',
    appId: '1:648016088742:ios:5ed86a0a1d9791c35b6e67',
    messagingSenderId: '648016088742',
    projectId: 'storyclub-4b1ad',
    storageBucket: 'storyclub-4b1ad.firebasestorage.app',
    iosBundleId: 'com.example.storyClub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlrkWMjIbTuVf4F7n-tt4YWdi_5z-tRX8',
    appId: '1:648016088742:web:2fc8851d0d925d8a5b6e67',
    messagingSenderId: '648016088742',
    projectId: 'storyclub-4b1ad',
    authDomain: 'storyclub-4b1ad.firebaseapp.com',
    storageBucket: 'storyclub-4b1ad.firebasestorage.app',
    measurementId: 'G-MBD843EMFP',
  );
}
